version: "2.4"

services:
  workspace:
    image: "angular-laravel"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "angular-laravel"
    working_dir: /var/www/html
    ports:
      - "10001:80"
    volumes:
        - .:/var/www/html
